name: Build jsc-android and publish

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android:2019-9-4

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '10.x'

    - name: Install packages
      run: |
        apt-get update
        apt-get install coreutils realpath curl git subversion python3.5 python3.5-dev ruby gperf -y
        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
      shell: bash

    - name: Install Android packages
      run: |
        sdkmanager \
          "cmake;3.10.2.4988404"
      shell: bash

    - name: Build
      run: |
        yarn clean
        yarn download
        yarn start
      shell: bash

    - name: Publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm publich
      shell: bash

